### PR TITLE
feat: fastify v5 support

### PR DESCRIPTION
**Pull request by tandibar**
Hi, I tried to make a PR for fastify v5 compatibility.

I did not have to make any code changes, all tests were passing after the fastify v5 update!

I also updated the README and added a compatibility section like other official fastify plugins do (see for example https://github.com/fastify/fastify-sensible/tree/master?tab=readme-ov-file#compatibility).

This should fix the issue #15 opened by @TobiasLC.

### CODE REVIEW

**Comment by hsynlms** [comment]
Thank you for the PR!

**Comment by tandibar** [comment]
Could you release a new version of this package with this change?

**Comment by hsynlms** [comment]
@tandibar I am going to release it very soon

**Comment by tandibar** [comment]
Is there anything I can do to support you to release the 3.0 version? This plugin is the last missing piece to update one of my projects to fastify 5.

**Comment by hsynlms** [comment]
@tandibar sorry for the delay. Fastify v5 support has been shipped in [v3.0.0](https://github.com/hsynlms/fastify-guard/releases/tag/v3.0.0).

**Pull request merged**
